- name: configure catalogue
  hosts: catalogue
  become: yes
  tasks:
  - name: enable nodejs 20
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: install nodejs
    ansible.builtin.dnf:
      name: nodejs
      state: present

  - name: create system user roboshop
    ansible.builtin.user:
      name: roboshop
      system: true
      home: /app
      shell: /sbin/nologin
      comment: "Roboshop system user"
  
  - name: delete the older app if present
    ansible.builtin.file:
      path: /app
      state: absent

  - name: create app directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: delete the catalogue tar
    ansible.builtin.file:
      path: /tmp/catalogue.zip
      state: absent

  - name: download catalogue
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip 
      dest: /tmp/catalogue.zip

  - name: unarchieve catalogue
    ansible.builtin.unarchive:
      src: /tmp/catalogue.zip
      dest: /app
      remote_src: yes

  - name: Run npm install command in app directory
    ansible.builtin.command: npm install
    args:
      chdir: "/app"
  
  - name: copy catalogue service
    ansible.builtin.template:
      src: catalogue.service
      dest: /etc/systemd/system/catalogue.service
  
  - name: copy mongo repo
    ansible.builtin.copy:
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo

  - name: Install mongodb client
    ansible.builtin.dnf:
      name: mongodb-mongosh
      state: present
  
  - name: check the mongodb data
    ansible.builtin.command: 
      cmd:  mongosh --host {{ MONGODB_HOST }} --quiet --eval 'db.getMongo().getDBNames().indexOf("catalogue")'
    register: mongodb_op
  
  - name: load mongodb setup 
    ansible.builtin.shell: mongosh --host {{ MONGODB_HOST }} </app/db/master-data.js # As this is not simple command redirection is present
    when: mongodb_op.stdout | int < 0
  
  - name: Demon service reload
    ansible.builtin.systemd_service:
      daemon_reload: true

  - name: start and enable catalogue
    ansible.builtin.service:
      name: catalogue
      enabled: yes
      state: restarted # as we run script multiple time, if state is started, it will not restart service as state is already present
      