- name: install and configure mysql
  hosts: mysql
  become: yes
  tasks:
    - name: install mysql
      ansible.builtin.dnf:
        name: mysql-server
        state: present
    
    - name: start and enable mysql
      ansible.builtin.service:
        name: mysqld
        enabled: yes
        state: restarted

    - name: setting password
      ansible.builtin.command: mysql_secure_installation --set-root-pass RoboShop@1
      