# cmd:: ansible-playbook -i localhost, -e '{"instances":["mongodb","catalogue","redis","user","cart","mysql","shipping","rabbitmq","payment"]}' roboshop.yaml
# OR cmd: ansible-playbook -i localhost, -e 'instances=[ "catalogue", "cart", "user", "mongodb", "redis", "shipping", "mysql","rabbitmq","payment", "frontend"]' roboshop.yaml
- name: create ec2 instance and Route53
  hosts: all
  connection: local
  vars:
    sg_id: "sg-0928fb36c1def6679"
    type_instance: "t3.micro"
    ami_id: "ami-0220d79f3f480ecf5"
    domain_name: manig.online
    env: dev
    task_to_do: create
    instances:
       - mongodb
       - catalogue
  tasks:
    # CREATE EC2 instance
    - name: Creating the ec2 instance
      amazon.aws.ec2_instance:
        security_group: "{{ sg_id }}"
        instance_type: "{{ type_instance }}"
        image_id: "{{ ami_id }}"
        name: "{{ item }}-{{ env }}"
        tags:
          Project: roboshop
          Environment: "{{ env }}"
          Component: "{{ item }}"
          Name: "{{ item }}-{{ env }}"
      loop: "{{ instances }}"
      register: ec2_output
      when: task_to_do == "create"
    
    - name: print the ec2_output
      ansible.builtin.debug:
        msg: "{{ ec2_output }}"
      when: task_to_do == "create"
    
    - name: create a route 53
      amazon.aws.route53:
        state: present
        zone: "{{ domain_name }}"
        record: "{{ item.item }}-{{ env }}.{{ domain_name }}"
        type: A
        ttl: 1
        value: "{{ item.instances[0].private_ip_address }}"
        wait: true
        overwrite: true
      loop: "{{ ec2_output.results }}"
      when: task_to_do == "create"
   
    - name: create a route 53
      amazon.aws.route53:
        state: present
        zone: "{{ domain_name }}"
        record: "roboshop-{{ env }}.{{ domain_name }}"
        type: A
        ttl: 1
        value: "{{ item.instances[0].public_ip_address }}"
        wait: true
        overwrite: true
      loop: "{{ ec2_output.results }}"
      when: 
        - item.item == "frontend"
        - task_to_do == "create"

    # Remove ec2 instance
    - name: delete the ec2 instances
      amazon.aws.ec2_instance:
        state: absent
        wait: false
        name: "{{ item}}-{{ env }}"
      loop: "{{ instances }}"
      when: task_to_do == "destroy"

    # Delete Route53
    - name: delete r53 records
      amazon.aws.route53:
        state: absent
        zone: "{{ domain_name }}"
        record: "{{ item }}-{{ env }}.{{ domain_name }}" 
        type: A
        ttl: 1
      loop: "{{ instances }}"
      when: task_to_do == "destroy"

    - name: delete r53 records # Delete for the roboshop
      amazon.aws.route53:
        state: absent
        zone: "{{ domain_name }}"
        record: "roboshop-{{ env }}.{{ domain_name }}" 
        type: A
        ttl: 1
      loop: "{{ instances }}"
      when: 
        - task_to_do == "destroy"
        - item == "frontend"
       

